(in-package :horn-system)
(defun list-of-nodes-p (lst)
  (every (lambda (item) (typep (type-of-node item) 'node-type)) lst))
(defun list-of-strings-p (lst)
  (every (lambda (item) (stringp item) lst)))
(deftype list-of-nodes ()
  '(satisfies list-of-nodes-p))
(deftype list-of-strings ()
  '(satisfies list-of-strings-p))
(deftype node-type ()
  '(member article heading paragraph list-node list-element src tag verbatim bold italic link image))
